# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    tva:
        class: Ecommerce\EcommerceBundle\Twig\Extension\TvaExtension
        tags:
            - { name: twig.extension }
