produits:
    path:     /
    defaults: { _controller: EcommerceBundle:Produits:produits }
    
categorieProduits:
    path:     /categorie/{categorie}
    defaults: { _controller: EcommerceBundle:Produits:categorie }
    
presentation:
    path:     /produit/{id}
    defaults: { _controller: EcommerceBundle:Produits:presentation  }
        
rechercheProduits:
    path:     /recherche
    defaults: { _controller: EcommerceBundle:Produits:rechercheTraitement }